permalink: pretty

theme: jekyll_patternbot

patternbot:
  font_url:
    "https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed:400,700|Neuton:300,400&display=swap"
  title: "Hearon Design"
  description: |
    The creation of a full personal brand, and the site developed in order to showcase the growth of my professional portfolio.
  colors:
    background: "--color-primary-light-grey"
    sidebar: "--color-primary-black"
    patterns:
  rationales:
    typefaces.primary: |
      Fira Sans Extra Condensed is the primary typeface throughout the website, used as the body copy and in general, the default font setting for most instances.

      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    typefaces.secondary: |
      Neuton was the secondary typeface used throughout the site in places of emphasis, such as headings, subtitles and navigation.

      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    colors.primary: |
      The colours primarily used throughout the site are simple greyscale, allowing for an emphasis on content rather than to distract.

      Deep blacks and high contrasting whites are used in order to add drama while still remaining professional and in tune with my personal visual identity.
    colors.secondary: |
      The secondary colours used throughout the site are vibrant golds taken from the set of banner images. The gold will be used for visual emphasis, in titling and hoverstates.

      The gold colours used are meant to add an air of distinction to the site. They are meant to be subtle, but still bright, and allow for a dramatic shift of focus if used correctly.
    colors.accent: |
      The secondary colours used throughout the site are vibrant golds taken from the set of banner images. The gold will be used for visual emphasis, in titling and hoverstates.

      The gold colours used are meant to add an air of distinction to the site. They are meant to be subtle, but still bright, and allow for a dramatic shift of focus if used correctly.
