title: "Landing Page: Assets"
description: |
  The term assets is used to describe any part of each portfolio page that is dedicated to the display of gathered final assets that are not expressly images, i.e. brand colours, fonts and basic style building blocks.
patterns:
  selfintro:
    title: "Welcome to my Portfolio - Introduction"
    description: |
       In the introduction of the project, the background information relevant to the client/project will be given. This will include anything that was given by the client or is common knowledge. It will present each particular study in the form of a problem that needed to be solved.
