title: "Test Layouts"
description: |
  The set of layout tests used throughout production in order to plan the site.
patterns:
  testprojectpage:
    title: "Project Page - In Testing"
    description: |
      This is the basic layout of each project page.
  testlandingpage:
    title: "Landing Page - In Testing"
    description: |
      This is the basic layout of the landing page.
