title: "Assets"
description: |
  The term assets is used to describe any part of each portfolio page that is dedicated to the display of gathered final assets that are not expressly images, i.e. brand colours, fonts and basic style building blocks.
patterns:
  colours:
    title: "Branding Example - Colour Palette"
    description: |
      For most branding projects, the brand will likely be looking for new and exciting changes to their colour palette. This building block allows for up to four key colours of any piece, and can be used even outside of basic branding packages to showcase and explain colour choices throughout any particular portfolio piece.
  BASE-siteblock:
    title: "Base"
    description: |
      Used as base duplicate for content.
