title: "About Me: Assets"
description: |
  The term assets is used to describe any part of each portfolio page that is dedicated to the display of gathered final assets that are not expressly images, i.e. brand colours, fonts and basic style building blocks.
